# Generated by Django 4.2.5 on 2026-04-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0006_syncconfig_deleted_syncconfig_deletedat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncconfig',
            name='timeAt',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='timeAt',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='syncqueueitem',
            name='timeAt',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
