# Generated by Django 4.2.5 on 2026-05-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0007_syncconfig_timeat_synclog_timeat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncconfig',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='syncqueueitem',
            name='timeAt',
        ),
    ]
