# Generated by Django 4.2.5 on 2026-04-10 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0071_alter_detailscomposeingredient_unique_together_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='city',
        #     name='hospital',
        # ),
        migrations.AddField(
            model_name='cash',
            name='name_language',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        # migrations.AddField(
        #     model_name='city',
        #     name='region',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.region'),
        # ),
        migrations.AlterField(
            model_name='cash',
            name='type_cash',
            field=models.CharField(blank=True, choices=[('CASH_COUNTERS', 'CASH_COUNTERS'), ('CASH_MAIN', 'CASH_MAIN'), ('CASH_BANK', 'CASH_BANK'), ('CASH', 'Cash'), ('MOMO', 'MTN MoMo'), ('OM', 'Orange Money')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CashTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('sync_version', models.BigIntegerField(default=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deletedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_shared', models.BooleanField(default=False, null=True)),
                ('language', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='hospital.cash')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cash_translation',
                'unique_together': {('cash', 'language')},
            },
        ),
    ]
