# Generated by Django 4.2.5 on 2026-04-28 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0080_remove_city_hospital_archive_timeat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplies',
            old_name='arri',
            new_name='arrival_date',
        ),
        # migrations.RemoveField(
        #     model_name='city',
        #     name='hospital',
        # ),
        migrations.AddField(
            model_name='bills',
            name='bills_date',
            field=models.DateField(blank=True, null=True),
        ),
        # migrations.AddField(
        #     model_name='city',
        #     name='region',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.region'),
        # ),
    ]
