# Generated by Django 4.2.5 on 2026-05-08 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0084_remove_city_hospital_city_region_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='city',
        #     name='hospital',
        # ),
        migrations.AddField(
            model_name='cash',
            name='difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cash',
            name='physical_amount',
            field=models.IntegerField(default=0),
        ),
        # migrations.AddField(
        #     model_name='city',
        #     name='region',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.region'),
        # ),
    ]
