# Generated by Django 4.2.5 on 2026-05-15 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0085_remove_city_hospital_cash_difference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='bills_date',
        ),
        # migrations.RemoveField(
        #     model_name='city',
        #     name='hospital',
        # ),
        # migrations.AddField(
        #     model_name='city',
        #     name='region',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.region'),
        # ),
        migrations.AddField(
            model_name='ingredient',
            name='threshold_max',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='threshold_min',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
