# Generated by Django 4.2.5 on 2026-06-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0072_remove_city_hospital_cash_name_language_city_region_and_more'),
        ('hospital', '0086_remove_bills_bills_date_remove_city_hospital_and_more'),
    ]

    operations = [
    ]
