# Generated by Django 4.2.5 on 2026-06-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0087_merge_20260617_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='name_language',
        ),
        # migrations.RemoveField(
        #     model_name='city',
        #     name='hospital',
        # ),
        migrations.AddField(
            model_name='bills',
            name='add_product',
            field=models.BooleanField(default=False, null=True),
        ),
        # migrations.AddField(
        #     model_name='city',
        #     name='region',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.region'),
        # ),
        migrations.DeleteModel(
            name='CashTranslation',
        ),
    ]
