# Generated by Django 4.2.5 on 2026-06-20 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0088_remove_cash_name_language_remove_city_hospital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='advance_payment',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='balance_due',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='contract_amount',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='estimated_guests',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='event_end',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='event_location',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='event_start',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='location',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='cateringinfo',
            name='bills',
        ),
        migrations.RemoveField(
            model_name='eventinfo',
            name='bills',
        ),
        migrations.AddField(
            model_name='bills',
            name='catering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.cateringinfo'),
        ),
        migrations.AddField(
            model_name='bills',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.eventinfo'),
        ),
        migrations.AddField(
            model_name='cash_movement',
            name='catering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catering_cash', to='hospital.cateringinfo'),
        ),
        migrations.AddField(
            model_name='cash_movement',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_cash', to='hospital.eventinfo'),
        ),
        migrations.AddField(
            model_name='cateringinfo',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('password', 'Password'), ('otp', 'OTP'), ('both', 'Password or OTP')], default='password', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_channel',
            field=models.CharField(choices=[('sms', 'sms'), ('email', 'email'), ('both', 'sms or email')], default='email', max_length=20),
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('otp_code', models.CharField(max_length=10)),
                ('purpose', models.CharField(default='verification', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('expiresAt', models.DateTimeField()),
                ('verifiedAt', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('sent_via_email', models.BooleanField(default=False)),
                ('sent_via_sms', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otp_verification',
                'ordering': ['-createdAt'],
                'indexes': [models.Index(fields=['email', 'otp_code'], name='otp_verific_email_400464_idx'), models.Index(fields=['phone', 'otp_code'], name='otp_verific_phone_c4c958_idx'), models.Index(fields=['expiresAt'], name='otp_verific_expires_13d5c1_idx')],
            },
        ),
    ]
