# Generated by Django 4.2.5 on 2026-06-20 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0089_remove_bills_advance_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_method',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_channel',
        ),
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
