# Generated by Django 4.2.5 on 2026-06-28 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0091_remove_city_hospital_city_region'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='city',
        #     name='hospital',
        # ),
        # migrations.AddField(
        #     model_name='city',
        #     name='region',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.region'),
        # ),
        migrations.AlterField(
            model_name='detailsbills',
            name='quantity_served',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
