# Generated by Django 4.2.5 on 2026-06-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0093_remove_city_hospital_city_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='catering',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='event',
        ),
        # migrations.RemoveField(
        #     model_name='city',
        #     name='hospital',
        # ),
        migrations.RemoveField(
            model_name='eventinfo',
            name='paid',
        ),
        migrations.AddField(
            model_name='cateringinfo',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caterings', to='hospital.patient'),
        ),
        # migrations.AddField(
        #     model_name='city',
        #     name='region',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.region'),
        # ),
        migrations.AddField(
            model_name='eventinfo',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hospital.patient'),
        ),
    ]
