# Generated by Django 4.2.5 on 2026-06-29 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0094_remove_bills_catering_remove_bills_event_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='city',
        #     name='hospital',
        # ),
        migrations.AddField(
            model_name='bills',
            name='catering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catering_bill', to='hospital.cateringinfo'),
        ),
        migrations.AddField(
            model_name='bills',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_bill', to='hospital.eventinfo'),
        ),
        # migrations.AddField(
        #     model_name='city',
        #     name='region',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.region'),
        # ),
        migrations.AddField(
            model_name='patientsettlement',
            name='catering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catering_settle', to='hospital.cateringinfo'),
        ),
        migrations.AddField(
            model_name='patientsettlement',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_settle', to='hospital.eventinfo'),
        ),
    ]
