# Generated by Django 4.2.5 on 2026-07-07 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0098_remove_city_hospital_city_region_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='city',
        #     name='hospital',
        # ),
        # migrations.AddField(
        #     model_name='city',
        #     name='region',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.region'),
        # ),
        migrations.AddField(
            model_name='combomenu',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='combomenu',
            name='is_valid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='composeingredient',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='composeingredient',
            name='is_valid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='composepreparation',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='composepreparation',
            name='is_valid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='is_valid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
