# Generated by Django 4.2.5 on 2026-07-08 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0099_remove_city_hospital_city_region_combomenu_code_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='city',
        #     name='hospital',
        # ),
        migrations.AddField(
            model_name='bills',
            name='is_valid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        # migrations.AddField(
        #     model_name='city',
        #     name='region',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.region'),
        # ),
        migrations.AddField(
            model_name='inventory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delete_inv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventory',
            name='is_valid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='stock_movement',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delete_stock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplies',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delete_sup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplies',
            name='is_valid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delete_bill', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stock_movement',
            name='is_valid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
