# Generated by Django 4.2.5 on 2026-07-08 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0101_remove_city_hospital_remove_supplies_arrival_date_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='city',
        #     name='hospital',
        # ),
        migrations.AddField(
            model_name='bills',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        # migrations.AddField(
        #     model_name='city',
        #     name='region',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.region'),
        # ),
        migrations.AddField(
            model_name='detailssupplies',
            name='storage_depots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.storage_depots'),
        ),
    ]
